apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Cloud Deploy pipeline for ML app
serialPipeline:
  stages:
    - targetId: dev-env
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          percentages: [25, 75, 100]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
description: Dev environment using Cloud Run
run:
  location: us-central1
  service: cloud-run-app
