steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-app-sh/cloud-run-ml-app:$SHORT_SHA',
        '.'
      ]
    id: 'Build Docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-app-sh/cloud-run-ml-app:$SHORT_SHA'
      ]
    id: 'Push to Artifact Registry'

  # Trigger Cloud Deploy release instead of direct deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', '$SHORT_SHA',
        '--delivery-pipeline=cloud-run-pipeline',
        '--region=us-central1',
        '--annotations=clouddeploy.googleapis.com/release-trigger=cloud-build',
        '--images=app=us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-app-sh/cloud-run-ml-app:$SHORT_SHA'
      ]
    id: 'Create Cloud Deploy Release'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: cloud-run-ml-app
