apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
  description: application deployment pipeline
serialPipeline:
  stages:
    - targetId: dev-env
      profiles: [dev]
      strategy:
        canary:
          trafficPercentages: [25, 75, 100]
    - targetId: qa-env
      profiles: [qa]
    - targetId: prod-env
      profiles: [prod]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
  description: Cloud Run development service
runTarget:
  region: us-west1
  service: cloud-run-ml-app-dev

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-env
  description: Cloud Run QA service
runTarget:
  region: us-central1
  service: cloud-run-ml-app-qa

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-env
  description: Cloud Run PROD service
  requireApproval: true
runTarget:
  region: us-central1
  service: cloud-run-ml-app-prod
