apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-ml-app-qa
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-app-sh/cloud-run-ml-app:$SHORT_SHA'
        env:
        - name: VERSION
          value: "$TAG"
