apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-ml-app-dev
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-app-sh/cloud-run-ml-app:$SHORT_SHA'
        env:
        - name: VERSION
          value: "$TAG"
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
