apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-ml-app-qa
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/_PROJECT_ID/_REPO/cloud-run-ml-app:$TAG
        env:
        - name: VERSION
          value: "$TAG"
