apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloud-run-ml-app
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/sales-prediction-app-sh/cloud-run-ml-app
profiles:
  - name: dev
    manifests:
      rawYaml:
        - deploy-dev.yaml
  - name: qa
    manifests:
      rawYaml:
        - deploy-qa.yaml
  - name: prod
    manifests:
      rawYaml:
        - deploy-prod.yaml
deploy:
  cloudrun: {}
